import {environment} from '../../../environments/environment';

export let AppSettings = {
  'languagesSupported': [{'code': 'en', 'description': 'ENGLISH'},
    {'code': 'fr', 'description': 'FRANÇAIS\n'},
    {'code': 'es', 'description': 'ESPAÑOL\n'}],
  'jobLevels': [{code: '01', description: 'VP or Equivalent'}, {code: '02', description: 'SVP or Equivalent'}],
  'currentCandidateJobLevels': [{code: '05', description: 'Director'}, {code: '06', description: 'Non Executive 10'},
    {code: '07', description: 'Vice President'}, {code: '08', description: 'Senior Vice President'},
    {code: '10', description: 'External'}],
  'jobIsOptions': [{code: '01', description: 'New'}, {code: '02', description: 'Existing VP/SVP Job'},
    {code: '03', description: 'Reclassification'}, {code: '04', description: 'Reorganization'}],
  'candidateTalentFlg': [{code: 2, description: 'HC - Executive Potential'},
    {code: 3, description: 'Executive Potential'}, {code: 4, description: 'Key Person'},
    {code: 5, description: 'Critical Resource'},
    {code: 6, description: 'No Flag'}, {code: 7, description: 'External'}],
  'approvals': {
    PositionsIdentifier: [
      {code: 4, description: 'VP / SVP HR Business Partner', zone: 'A', order: 1},
      {code: 3, description: 'SCT', zone: 'A', order: 2},
      {code: 2, description: 'Leadership', zone: 'A', order: 3},
      {code: 1, description: 'CEO/CHRO', zone: 'A', order: 4},
      {code: 1, description: 'VP / SVP HR Business Partner', zone: 'B', order: 1},
      {code: 2, description: 'Leadership', zone: 'B', order: 2}]
  },
  'appointmentStatuses': [{code: 1, description: 'Pending Job Approval'},
    {code: 2, description: 'Job Approved'},
    {code: 3, description: 'Pending Candidate Approval'},
    {code: 4, description: 'Pending Announcement'},
    {code: 5, description: 'Announced'},
    {code: 6, description: 'Approved Effective'}
  ],
  'replacementReasons': [ {code: 1, description: 'Transfer'},
    {code: 2, description: 'Resignation / Termination'},
    {code: 3, description: 'Retirement'},
    {code: 4, description: 'New Position / Complement'},
    {code: 5, description: 'Reorganization'}
  ],
  'LRPSuccessorToJob': [ {code: 1, description: 'Next Move'},
    {code: 2, description: '1 Move'},
    {code: 3, description: '2+ Move'},
    {code: 4, description: 'Emergency'},
    {code: 5, description: 'No'},
    {code: 6, description: 'Not applicable'}
  ],
  'acceptedEmailDomains': ['scotiabank.com',
    'scotiamcleod.com',
    'scotiawealth.com',
    'scotiaitrade.com',
    'scotiafunds.com',
    'scotiaprivateclient.com',
    'scotiacb.com.mx',
    'scotiadbg.com',
    'scotiawaterous.com',
    'scotiaam.com',
    'tradefreedom.com',
    'scotiamcleoddirect.com',
    'br.scotiabank.com',
    'scotiapatrimoine.com',
    'scotiabank.cl'],
// /preLogin, API End points
  'apiEP': {
    'apiURL_BASE': `${environment['apiURL_BASE']}`,
    'apiGetUserInfo': '/getUserInfo',
    'apiGetUsers': '/getUsers',
    'apiGetBusinessLines': '/getBusinessLines',
    'apiGetAppointments': '/getAppointments',
    'apiGetAppointment': '/getAppointment',
    'apiUpdateAppointment': '/updateAppointment',
    'apiDeleteAppointment': '/deleteAppointment',
    'apiCreateAppointment': '/createAppointment',
    'apiUpdateApproval': '/updateApproval',
    'apiSendRequestApproval': '/sendRequestApproval',
    'apiSetApproval': '/setApproval',
    'apiUploadFile': '/uploadFile',
    'apiDownloadFile': '/getFile',
    'apiDeleteFile': '/deleteFile',
    'apiRequestExport': '/requestExport',
    'apiDownloadExport': '/downloadExport',
    'apiGetAllDelegations': '/getAccessDelegations',
    'apiGetAccessDelegationById': '/getAccessDelegation',
    'apiCreateAccessDelegation': '/createAccessDelegation',
    'apiUpdateAccessDelegation': '/updateAccessDelegation',
    'apiDeleteAccessDelegation': '/deleteAccessDelegation'

  },
  'reportExcelFileNAme': 'VP+ Appointments Tracking Sheet.csv',
  'maxUploadFileSize': 10000000,
  'appMinDate': new Date(1990, 1, 1),
  'appMaxDate': new Date(2100, 12, 31),
};

export let AppNotificationsMSG = {
  'deletionQuestionMsg': 'Do you  really want to delete the record ?',
  'deletionTitle': 'Delete',
  'deletionConfirmationMsg': 'Record successfully deleted !',
  'deactivationConfirmationMsg': 'Deactivation was successful !',
  'saveConfirmedMsg': 'Record successfully saved !',
  'updateConfirmedMsg': 'Record successfully updated !',
  'insertMSG': 'Record successfully created',
  'notificationTitle': 'Notification',
  'largerSearchPeriod': 'Your search period can\'t be greater than 60 days.',
  'errorTitle': 'Error',
  'warningTitle': 'Warning',
  'saveConfirmedMassUpdate': 'Mass updated completed !',
  'saveConfirmedMassDelete': 'Deletion is successful!',
  'maxUpdatesMaxList': 'You can\'t add more than 50 agents to mass update list!',
  'maxUpdatesMaxUsersList': 'You can\'t add more than 20 users to mass update list!',
  'loadingActiveDirectoryInfo': 'Loading Active Directory user\'s profile...',
  'loadingAppointments': 'Loading appointments list....',
  'errorLoadingActiveDirectoryInfo': `An error occurred while loading your Active Directory profile.
      Please start new session in few seconds! If the problem persists contact the administrator.`
}
